on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.69.0  # MSRV

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: System dependencies
        run: |
          mkdir -p /home/runner/.local/share/authenticator-rs/
          sudo apt-get update
          sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev libsqlite3-dev libgtk-3-dev

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1

      - name: Formatting
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build

      - name: Tests
        run: cargo test

      - name: Clippy
        run: cargo clippy --all -- -D warnings
